### ISSUE TITLE
Image is too big for OMERO.figure

### ISSUE THREAD

**Issue by dnmason** [ome/omero-figure#280]
We've recently run into an issue (figure 3.2.1 on a 5.4.5-ice36-b83 server) with tiled images that cannot be imported into OMERO.figure and give the error "Image '{NAME}' is too big for OMERO.figure.

![toobig](https://user-images.githubusercontent.com/7047957/38927710-90eaeed8-42fe-11e8-853f-6e6287b5fb72.PNG)

One image in question is 8460 x 8460 pixels of 16bit data and 4 channels. I can't find any documentation about a file size limit other than [issue 37](https://github.com/ome/omero-figure/issues/37) which led me to try a larger paper size. Going up to A0 still gives the same error.

The only workaround I've found is to downsample the images and keep a high-res for analysis and low res for figure, but this seems a bit perverse.

**Comment by will-moore** [comment]
This has been a known issue from day-1: Figure doesn’t (yet) support tiled images but we are working on support for them:
https://github.com/ome/omero-figure/pull/243

This is largely complete but there’s a few related issues that have come up:
 - Export resolution. For large images, you should be able to choose a maximum export dpi
 - ROI stroke widths: Currently the stroke width of shapes is fixed on the pixels of the image, so when you zoom an image out a lot, the lines get thinner. This means that for big images, you need stroke widths of e.g. 100 before you can see them! It's also inconsistent with the way OMERO.iviewer works, where stroke widths are always the same, regardless of zoom. So, we are looking to move OMERO.figure to this model, but that is a breaking change for all existing figures (lines will appear different widths from before) so we need to consider how to handle this.

Any feedback welcome!

**Comment by will-moore** [comment]
I was referring to PDF export above. When you export as TIFF, all images are resampled to 300dpi, but for PDF export you can have different panels embedded at different dpi resolutions.

How large are your images?
OMERO generates pyramids of tiles for images over approx 3k x 3k but this can be configured.
Even for images over this size, OMERO.figure *can* include them without #243 if they are small enough to be rendered as a single plane. The limit for this depends on the rendering engine memory but can also be configured (default is 12k x 12k). However, OMERO.figure currently rejects images over 5k x 5k because this gets slower etc.

**Comment by dnmason** [comment]
The ones I'm working with are about 8k x 8k.

**Comment by will-moore** [comment]
If you *really* can't wait for the next release, you *could* work around this by editing the JavaScript in the concatenated file ```omero_figure/static/figure/figure.js```, setting the limit in the two lines that have this code:
```
if (data.size.width * data.size.height > 5000 * 5000) {
```
to e.g. ```10000 * 10000```. 
That should allow OMERO.figure to add the image, but you will find it slow to render.

However, only do this if you are happy making changes to the code, updating the static file in your web server and testing with your images etc on a non-production server first. Otherwise it will be best to wait for the next release.

**Comment by dnmason** [comment]
I think I'll keep an eye on the PR and just wait. I appreciate the details though. Always nice to see how something works under the hood.
