### ISSUE TITLE
How to develop this plugin with remote server?

### ISSUE THREAD

**Issue by thejohnhoffer** [ome/omero-figure#299]
For development with a remote Omero server, I'm setting chrome to make redirects like this: 

from
`http://localhost:8000/demo/%7B%%20url%20'webgatewayopen_with/`
to
`https://omero.hms.harvard.edu/webgateway/open_with/?_=1234567891234`

from
`http://localhost:8000/demo/%7B%%20url%20'webgatewa/render_image/548111/0/0/?`
to
`https://omero.hms.harvard.edu/figure/render_scaled_region/548111/0/0/?&region=-8160,-16416,48960,48960&`

To my surprise, this works. Is there a proper way to configure a plugin like `figure` to use an external server?

**Comment by will-moore** [comment]
I'm kinda surprised that works too!
The demo build was only created to build the static site at http://figure.openmicroscopy.org/demo/#file/1 which doesn't happen very often, so that build etc is a little fragile. The way that you are expected to add images from an OMERO server (which is 'public' or you are already logged in) is described at
http://figure.openmicroscopy.org/2015/10/12/omero-figure-demo-app-how-it-works.html.
If you paste the URL to an image viewer (e.g. http://idr.openmicroscopy.org/webclient/img_detail/179693/) into the Add Images dialog, the OMERO.figure will use this to load the JSON and images it needs, and will also save the host URL in the figure file.

In due course, we are planning to use a public OMERO.web install of OMERO.figure as a demo of the app, so http://figure.openmicroscopy.org/demo/#file/1 will not be needed and we will likely remove all the demo build from the figure repo to avoid the maintenance cost. Unless we hear that the demo build is important as a way of running OMERO.figure for developers without needing to install in OMERO.web?

**Comment by thejohnhoffer** [comment]
I think allowing an isolated build of OMERO.figure lowers the barrier to entry for developers looking to make a small contribution, especially if it's just a small UI change or something.

I'm sure I could probably follow [these build instructions here](https://docs.openmicroscopy.org/omero/5.4.0/sysadmins/unix/install-web/walkthrough/omeroweb-install-ubuntu-ice3.6.html) to install OMERO.web and then follow [the instructions in this repo](https://github.com/ome/omero-figure#installing-from-pypi) to add OMERO.figure as a plugin. Maybe it would just be helpful for beginners to just link to the following page in the readme: https://docs.openmicroscopy.org/omero/5.4.0/sysadmins/unix/install-web/web-deployment.html

**Comment by thejohnhoffer** [comment]
👍

**Comment by will-moore** [comment]
Thanks for your feedback - We'll keep it in mind when considering the future of the demo build.
