### ISSUE TITLE
Add possibility to draw shapes

### ISSUE THREAD

**Issue by Trefex** [ome/omero-figure#79]
Will,

Our uses would love to have the possibility to place arrows, or other shapes, but mostly arrows on their Figure.

That way it would reduce the necessity to do this in another program later on.

What do you think?

Linked to that, our group here sometimes draws a box around the panel labels so that it looks more "straight". Having the possibility for shapes would allow to both annotate the panels and their labels nicely.

**Comment by will-moore** [comment]
I know that this would be very useful, but I need to consider it a lot first.
I don't want to replicate too many features that are available elsewhere, otherwise I'll end up trying to build Illustrator, and not doing a very good job of it.
However, I realise that annotations on images are an important part of figures.
There are kind of 2 kinds of "arrows, shapes etc": Those that are on a single image (equivalent to ROIs on images in OMERO) and those that are global (over the whole figure). The same is true for labels. Currently I only allow labels per image: you can't just add a label to the figure on it's own.
Do you mostly need shapes within a panel (so when you drag the panel, the shape stays with it) or as part of the whole figure?

Can you give me a screenshot of your "box around the panel labels" to help me understand this?
Currently my positioning of labels is a little imprecise when I export to PDF/TIFF (I need to improve this), so I'd worry that a separate box would not be perfectly aligned to the label.
The same is true of arrows etc. I'd want to be sure that I could reproduce them pixel-perfect on export, so that they don't end up pointing to the wrong thing!

**Comment by Trefex** [comment]
@will-moore Talked to our users. Let's split it up in two then.

1. Panel-related shapes

For this, mostly arrows would be important for now. In an ideal setting, the arrow is anchored to the panel, so that if you move it, it moves with the panel. 

2. Out-side panel related shapes

Here, we are talking about boxes and other stuff. Arrows would not be required. This would allow people to put some basic annotation on the Figure.

Right now, priority would be 1. as 2. is further away from "sciency" stuff.

On the basic premise of re-creating Illustrator, here are my thoughts. Right now, I see a clear interest for users to move to OMERO to be able to use OMERO.figure in particular. The time to create a basic figure is reduced from 4-5 hours to 15-20 mins. **That** is absolutely impressive! Having said that, from a reproducibility point of view, it will be much more rigourous if a scientist could write that the figures were prepared with OMERO.figure only and that the sources are somewhere accessible, rather than saying half of the Figure was done in OMERO and the other half in Illustrator again. 

I get where you come from, and I'm not saying we should add anything and everything, but with the color wheel, potential arrows, multiple pages, you will cover 90% of the needs anyway which would not require further processing in general.

For the "box around panel labels" I sent you examples via email.

**Comment by will-moore** [comment]
Thanks for that. Certainly "panel-related shapes" is much more attractive and feasible to tackle initially.
I'll start to look into it, since it has been requested by others (as you'd expect)!
But no idea how long this will take!

Thanks for your feedback (and email).

**Comment by will-moore** [comment]
Just a note to say that I'm working on this slowly, but there's a lot to do!
I'm generally using ImageJ as a guide for the adding shapes behaviour.

![screen shot 2015-05-27 at 13 52 56](https://cloud.githubusercontent.com/assets/900055/7836406/d314d81e-0477-11e5-93c5-a280c48193b2.png)

**Comment by Trefex** [comment]
Hi @will-moore. Looks nice already! How about arrows and stuff? (just asking) :smile:

**Comment by will-moore** [comment]
Arrows: Done!
Next is Ellipses, then I'll leave segmented lines/shapes until everything else is working (less critical).

![Uploading Screen Shot 2015-05-28 at 16.37.29.png…]()

**Comment by will-moore** [comment]
Arrows: Done!
Next is Ellipses, then I'll leave segmented lines/shapes until everything else is working (less critical).

![screen shot 2015-05-28 at 16 37 29](https://cloud.githubusercontent.com/assets/900055/7864268/057203ea-0559-11e5-9862-d94b798c0bb6.png)

**Comment by Trefex** [comment]
:+1:
